tasks:
    - name: aws-cli
      env:
        AWS_CLI_AUTO_PROMPT: on-partial
      init: 
        cd ~/workspace
        curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
        sudo installer -pkg AWSCLIV2.pkg -target /
        cd aws-bootcamp-cruddur-2023
vscode:
  extensions:
    - 42Crunch.vscode-openapi